#!/usr/bin/env bash

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Настройка бара
sketchybar --bar \
  position=top \
  height=35 \
  blur_radius=30 \
  color=0x40000000

# Дефолтные стили
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# Регистрируем кастомный ивент от AeroSpace
sketchybar --add event aerospace_workspace_change

# Создаём элемент для каждого воркспейса
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
      background.color=0x44ffffff \
      background.corner_radius=5 \
      background.height=20 \
      background.drawing=off \
      label="$sid" \
      click_script="aerospace workspace $sid" \
      script="$PLUGIN_DIR/aerospace.sh $sid"
done

# Общие настройки фона-«пилюли» для правых виджетов
widget_bg=(
  background.color=0x44ffffff
  background.corner_radius=6
  background.height=26
  background.drawing=on
)

sketchybar --add item clock right --set clock icon="⏰" width=115 align=center \
    "${widget_bg[@]}" update_freq=1 script="$PLUGIN_DIR/clock.sh"

sketchybar --add item sp_clock right --set sp_clock width=8 \
    icon.drawing=off label.drawing=off background.drawing=off

sketchybar --add item calendar right --set calendar icon="󰃭" width=133 align=center \
    "${widget_bg[@]}" update_freq=30 script="$PLUGIN_DIR/calendar.sh"

sketchybar --add item sp_calendar right --set sp_calendar width=8 \
    icon.drawing=off label.drawing=off background.drawing=off

sketchybar --add item battery right --set battery width=73 align=center \
    "${widget_bg[@]}" update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery power_source_change system_woke

sketchybar --add item sp_battery right --set sp_battery width=8 \
    icon.drawing=off label.drawing=off background.drawing=off

sketchybar --add item cpu right --set cpu icon="󰻠" width=73 align=center \
    "${widget_bg[@]}" update_freq=30 script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item sp_cpu right --set sp_cpu width=8 \
    icon.drawing=off label.drawing=off background.drawing=off

sketchybar --add item ram right --set ram icon="󰍛" width=73 align=center \
    "${widget_bg[@]}" update_freq=30 script="$PLUGIN_DIR/ram.sh"

# Обновляем бар при старте
sketchybar --update
